### ISSUE TITLE
As a user, I want to view a Notice of Articles output .......

### ISSUE THREAD

**Issue by sienna-freshworks** [bcgov/fwben#175]
## Description:

**Acceptance Criteria:**
NEED DEETS
 
**Definition of Ready:**
- [ ] All dependancies resolved
- [ ] AC is defined
- [ ] Estimated
- [ ] Estimation is small enough to be completed in a sprint
- [ ] Approved by SMEs / PO

**Definition of Done:**
- [ ] AC is met
- [ ] Unit tests created and passing
- [ ] E2E tests created and passing
- [ ] Code review completed
- [ ] Test cases created and passing
- [ ] Regression tests passing
- [ ] All bugs/dependencies resolved

**Comment by sienna-freshworks** [comment]
CLosing because not using stories anymore
